@startuml 演習6-4-2
left to right direction
actor 客 as customer
actor ベンダー as vendor

rectangle 自動販売機 {
    usecase ボタン as button
    usecase 料金装置 as price 
    usecase ベンダー装置 as vendormachine
}

customer --> button
customer --> price
customer --> vendormachine
price <-- vendor
@enduml