@startuml 7-2
|営業部門|
start
:発注;
|販売代理店|
:受注;
:在庫調査;
if () is (在庫あり) then
:;
note right
作図の都合上、
ダミーの
アクティビティ
を記述
end note
else (在庫なし)
|製造部門|
:製造;
endif
|販売代理店|
:発送;
|営業部門|
:検収/支払い;
|販売代理店|
:入金確認;
stop
@enduml