@startuml 6-3
left to right direction
actor 申請者#DDDDDD;line:black;line.bold;
actor 看護師#DDDDDD;line:black;line.bold;
rectangle 予約システム {
usecase メニューに行く
usecase 登録する
usecase 順番を見る
usecase 今の順番を見る
}
今の順番を見る <-- 看護師 
申請者--> メニューに行く
申請者--> 登録する
申請者--> あなたの順番を見る
申請者--> 今の順番を見る
@enduml