@startuml 演習6-5-2
left to right direction
actor ユーザー as user
actor 光センサー as sensor

rectangle ライントレーサー {
    usecase 電源SV as powersupply
    usecase 右モーターを動かす as right
    usecase 左モーターを動かす as left
}

user --> powersupply
sensor --> right
sensor --> left
@enduml