@startuml 6-3
[*] -right-> メニュー: 接続
メニュー --> 予約と確認: 登録
予約と確認 --> メニュー: 取り消し
予約と確認 --> あなたの順番: 名前と電話番号を入力
予約と確認 --> あなたの順番: 順番の確認
あなたの順番 --> メニュー: 順番を表示
メニュー --> 今の順番: 確認
今の順番 --> メニュー: 番号を一つ増やす
メニュー -right-> [*]: やめる
@enduml